#pragma once

// Enum for function return valuesS
enum RetVal {
	SUCCESS,
	FAILED,
	UNABLE_TO_FETCH,
	UNABLE_TO_CONVERT,
	COM_INIT_FAILED,
	SEC_INIT_FAILED,
	WLOCATOR_CREATION_FAILED,
	CONNECT_SERVER_FAILED,
	SET_PROXY_BLANKED_FAILED,
	QUERY_EXEC_FAILED,
	UNSUPPORTED_TYPE
};
